import React from 'react';
export const metadata = {
    title: {
       absolute: "About"
    },
    // description use for SEO
    description: "Generated by create next app",
    // keyword use for SEO
    keywords: "next.js, react, javascript",
};
const AboutPage = () => {
    return (
        <div>
            this is about page
        </div>
    );
};

export default AboutPage;